# Generated by Django 4.1.13 on 2024-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_a_votes', models.IntegerField(default=0)),
                ('party_b_votes', models.IntegerField(default=0)),
                ('party_c_votes', models.IntegerField(default=0)),
                ('party_d_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
