# Generated by Django 4.1.13 on 2024-06-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evm', '0002_votecount_count_a_votecount_count_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votecount',
            name='count_d',
        ),
    ]
